name: CI - Project 2

on:
  push:
    branches: [ main ]
    paths:
      - 'project_2/**'
      - ".github/workflows/project_2_ci.yml"
  pull_request:
    branches: [ main ]
    paths:
      - 'project_2/**'
      - ".github/workflows/project_2_ci.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: project_2/yarn.lock

      - name: Install dependencies
        working-directory: ./project_2
        run: yarn install --frozen-lockfile

      - name: Run Lint
        working-directory: ./project_2
        run: yarn lint

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: project_2/yarn.lock

      - name: Install dependencies
        working-directory: ./project_2
        run: yarn install --frozen-lockfile

      - name: Check and Fix Formatting
        working-directory: ./project_2
        run: yarn format

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: project_2/yarn.lock

      - name: Install dependencies
        working-directory: ./project_2
        run: yarn install --frozen-lockfile

      - name: Run Tests with Coverage
        working-directory: ./project_2
        run: yarn test:ci
